// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdWXkWCZSy2XdxEjW0qlwzKRz7YkzsgM8',
    appId: '1:508999367878:web:acf54a78fb52cec1ce2bc7',
    messagingSenderId: '508999367878',
    projectId: 'connectpamodziv04',
    authDomain: 'connectpamodziv04.firebaseapp.com',
    storageBucket: 'connectpamodziv04.appspot.com',
    measurementId: 'G-Z4HCMWKCC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1hjtXU3HdXthsb8tQ7n7cbf5_LglrpOc',
    appId: '1:508999367878:android:10cd0ded663d2435ce2bc7',
    messagingSenderId: '508999367878',
    projectId: 'connectpamodziv04',
    storageBucket: 'connectpamodziv04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcAcgyvgWsB643U1pyzRTXOupRLnqm7Zs',
    appId: '1:508999367878:ios:6a92b36f608c7ae2ce2bc7',
    messagingSenderId: '508999367878',
    projectId: 'connectpamodziv04',
    storageBucket: 'connectpamodziv04.appspot.com',
    iosBundleId: 'com.example.connectpamodziv04',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcAcgyvgWsB643U1pyzRTXOupRLnqm7Zs',
    appId: '1:508999367878:ios:6a92b36f608c7ae2ce2bc7',
    messagingSenderId: '508999367878',
    projectId: 'connectpamodziv04',
    storageBucket: 'connectpamodziv04.appspot.com',
    iosBundleId: 'com.example.connectpamodziv04',
  );
}
